export function useLoadingMessageGenerator() {
  let progress = 0
  let lastMessage = ''

  const loadingMessages = [
    '正在扫描文件',
    '删除临时文件',
    '正在获取用户数据',
    '加载配置信息',
    '正在验证权限',
    '处理请求中',
    '正在连接服务器',
    '更新数据库记录',
    '正在下载更新包',
    '解析数据内容',
    '正在初始化系统',
    '准备就绪',
    '正在计算哈希值',
    '同步云端数据',
    '正在压缩文件',
    '检查网络连接',
    '正在渲染界面',
    '保存用户设置',
    '正在备份数据',
    '验证文件完整性',
    '正在安装组件',
    '清理缓存数据',
    '正在启动服务',
    '加载资源文件',
    '正在分析日志',
    '优化性能',
    '正在刷新列表',
    '生成报告文件',
    '正在搜索内容',
    '上传文件中',
    '正在准备下载',
    '解码媒体流',
    '正在索引文件',
    '验证用户身份',
    '正在排队任务',
    '准备打印',
    '正在转换格式',
    '计算存储空间',
    '正在重启服务',
    '加载字体资源'
  ]

  return {
    inc: function () {
      // 随机决定是否重复上一条消息 (约20%的概率重复)
      const shouldRepeat = Math.random() < 0.2 && lastMessage !== ''

      const message = shouldRepeat
        ? lastMessage
        : loadingMessages[Math.floor(Math.random() * loadingMessages.length)]
      lastMessage = message

      // 生成递增幅度：0 或 0.01-0.05 之间的随机值
      const increment = Math.random() < 0.3 ? 0 : Math.random() * 0.04 + 0.01
      progress = Math.min(1, progress + increment)

      return {
        message: message,
        progress: parseFloat(progress.toFixed(2)) * 100 // 保留2位小数
      }
    },
    reset: () => (progress = 0)
  }
}

type ExtractPromise<T> = T extends Promise<infer U> ? U : T
type Hwinfo = ExtractPromise<ReturnType<typeof window.api.hwinfo>>

export function useTestHwinfo() {
  return {
    version: '5.27.11',
    system: {
      manufacturer: 'Gigabyte Technology Co., Ltd.',
      model: 'H610M H V3 DDR4',
      version: '-CF',
      serial: 'Default string',
      uuid: '03560274-043c-05ac-b906-4c0700080009',
      sku: 'Default string',
      virtual: false
    },
    bios: {
      vendor: 'American Megatrends International, LLC.',
      version: 'F6',
      releaseDate: '2025-06-19',
      revision: '',
      serial: ''
    },
    baseboard: {
      manufacturer: 'Gigabyte Technology Co., Ltd.',
      model: 'H610M H V3 DDR4',
      version: 'x.x',
      serial: '',
      assetTag: '',
      memMax: 68719476736,
      memSlots: 2
    },
    chassis: {
      manufacturer: '',
      model: '',
      type: 'Desktop',
      version: '',
      serial: '',
      assetTag: '',
      sku: ''
    },
    os: {
      platform: 'Windows',
      distro: 'Microsoft Windows 11 企业版',
      release: '10.0.26220',
      codename: '',
      kernel: '10.0.26220',
      arch: 'x64',
      hostname: 'HHPC',
      fqdn: 'HHPC',
      codepage: '936',
      logofile: 'windows',
      serial: '00328-90000-00000-AAOEM',
      build: '26220',
      servicepack: '0.0',
      uefi: true,
      hypervisor: true,
      remoteSession: false
    },
    uuid: {
      os: '66e9ccf2-1aa4-4358-8cf2-1e300bf53e94',
      hardware: '03560274-043c-05ac-b906-4c0700080009',
      macs: ['00:15:5d:f5:f0:97', '00:50:56:c0:00:01', '00:50:56:c0:00:08', '74:56:3c:ac:b9:4c']
    },
    versions: {
      kernel: '10.0.26220',
      apache: '',
      bash: '',
      bun: '',
      deno: '',
      docker: '',
      dotnet: '4.8.09221',
      fish: '',
      gcc: '',
      git: '2.39.1.windows.1',
      grunt: '',
      gulp: '',
      homebrew: '',
      java: '21.0.3',
      mongodb: '',
      mysql: '',
      nginx: '',
      node: '24.10.0',
      npm: '11.6.1',
      openssl: '0.0.0',
      perl: '',
      php: '',
      pip3: '22.0.4',
      pip: '22.0.4',
      pm2: '',
      postfix: '',
      postgresql: '',
      powershell: '5.1.26100.6780:',
      python3: '3.10.11',
      python: '3.10.4',
      redis: '',
      systemOpenssl: '',
      systemOpensslLib: '',
      tsc: '4.7.2',
      v8: '14.0.365.4-electron.0',
      virtualbox: '',
      yarn: '',
      zsh: ''
    },
    cpu: {
      manufacturer: 'Intel',
      brand: '12th Gen Intel® Core™ i5-12400F',
      vendor: 'GenuineIntel',
      family: '6',
      model: '151',
      stepping: '2',
      revision: '',
      voltage: '',
      speed: 2.5,
      speedMin: 2.5,
      speedMax: 2.5,
      governor: '',
      cores: 12,
      physicalCores: 6,
      performanceCores: 12,
      efficiencyCores: 0,
      processors: 1,
      socket: 'LGA1700',
      flags: 'de pse mce sep mtrr mca cmov psn clfsh ds acpi mmx fxsr sse sse2 ss htt tm ia64 pbe',
      virtualization: true,
      cache: {
        l1d: 294912,
        l1i: 196608,
        l2: 7864320,
        l3: 18874368
      }
    },
    graphics: {
      controllers: [
        {
          vendor: 'Shanghai Best Oray Information Technology Co., Ltd.',
          model: 'OrayIddDriver Device',
          bus: '',
          vram: 0,
          vramDynamic: true,
          subDeviceId: undefined
        },
        {
          vendor: 'NVIDIA',
          model: 'NVIDIA GeForce GTX 1660 SUPER',
          bus: 'PCI',
          vram: 6144,
          vramDynamic: true,
          subDeviceId: '407D1458'
        }
      ],
      displays: [
        {
          vendor: '',
          model: '默认监视器',
          deviceName: '\\\\.\\DISPLAY1',
          main: true,
          builtin: false,
          connection: 'HDMI',
          resolutionX: 3840,
          resolutionY: 2160,
          sizeX: 53,
          sizeY: 30,
          pixelDepth: 32,
          currentResX: 1920,
          currentResY: 1080,
          positionX: 0,
          positionY: 0,
          currentRefreshRate: 59
        }
      ],
      monitors: [
        {
          vendor: 'ACR',
          code: '0704',
          model: 'VG240Y P',
          serial: '2453817919',
          instanceId: 'DISPLAY\\ACR0704\\5&1afdd5bf&0&UID4356_0',
          builtin: false,
          connection: 'HDMI'
        },
        {
          vendor: 'BNQ',
          code: '802E',
          model: 'BenQ PD2700U',
          serial: 'ETY7L00616CL0',
          instanceId: 'DISPLAY\\BNQ802E\\5&1afdd5bf&0&UID4357_0',
          builtin: false,
          connection: 'DP'
        }
      ]
    },
    net: [
      {
        iface: '以太网 2',
        ifaceName: 'Realtek PCIe GbE Family Controller #2',
        default: true,
        ip4: '10.0.0.223',
        ip4subnet: '255.255.0.0',
        ip6: '',
        ip6subnet: '',
        mac: '74:56:3c:ac:b9:4c',
        internal: false,
        virtual: false,
        operstate: 'up',
        type: 'wired',
        duplex: '',
        mtu: '',
        speed: 1000,
        dhcp: true,
        dnsSuffix: 'lan',
        ieee8021xAuth: 'Unknown',
        ieee8021xState: 'Unknown',
        carrierChanges: 0
      },
      {
        iface: 'VMware Network Adapter VMnet1',
        ifaceName: 'VMware Virtual Ethernet Adapter for VMnet1',
        default: false,
        ip4: '192.168.74.1',
        ip4subnet: '255.255.255.0',
        ip6: '',
        ip6subnet: '',
        mac: '00:50:56:c0:00:01',
        internal: false,
        virtual: true,
        operstate: 'up',
        type: 'wired',
        duplex: '',
        mtu: '',
        speed: 100,
        dhcp: true,
        dnsSuffix: '',
        ieee8021xAuth: 'Unknown',
        ieee8021xState: 'Unknown',
        carrierChanges: 0
      },
      {
        iface: 'VMware Network Adapter VMnet8',
        ifaceName: 'VMware Virtual Ethernet Adapter for VMnet8',
        default: false,
        ip4: '192.168.180.1',
        ip4subnet: '255.255.255.0',
        ip6: '',
        ip6subnet: '',
        mac: '00:50:56:c0:00:08',
        internal: false,
        virtual: true,
        operstate: 'up',
        type: 'wired',
        duplex: '',
        mtu: '',
        speed: 100,
        dhcp: true,
        dnsSuffix: '',
        ieee8021xAuth: 'Unknown',
        ieee8021xState: 'Unknown',
        carrierChanges: 0
      },
      {
        iface: 'Loopback Pseudo-Interface 1',
        ifaceName: 'Loopback Pseudo-Interface 1',
        default: false,
        ip4: '127.0.0.1',
        ip4subnet: '255.0.0.0',
        ip6: '::1',
        ip6subnet: 'ffff:ffff:ffff:ffff:ffff:ffff:ffff:ffff',
        mac: '00:00:00:00:00:00',
        internal: true,
        virtual: false,
        operstate: 'down',
        type: '',
        duplex: '',
        mtu: '',
        speed: null,
        dhcp: false,
        dnsSuffix: '',
        ieee8021xAuth: 'Unknown',
        ieee8021xState: 'Unknown',
        carrierChanges: 0
      },
      {
        iface: 'vEthernet (Default Switch)',
        ifaceName: 'vEthernet (Default Switch)',
        default: false,
        ip4: '172.18.192.1',
        ip4subnet: '255.255.240.0',
        ip6: 'fe80::d075:ada4:7003:efd1',
        ip6subnet: 'ffff:ffff:ffff:ffff::',
        mac: '00:15:5d:f5:f0:97',
        internal: false,
        virtual: true,
        operstate: 'down',
        type: '',
        duplex: '',
        mtu: '',
        speed: null,
        dhcp: false,
        dnsSuffix: '',
        ieee8021xAuth: 'Unknown',
        ieee8021xState: 'Unknown',
        carrierChanges: 0
      }
    ],
    memLayout: [
      {
        size: 17179869184,
        bank: 'BANK 0/0',
        type: 'DDR4',
        ecc: false,
        clockSpeed: 2666,
        formFactor: 'DIMM',
        manufacturer: 'Kimtigo Semiconductor (HK) Limited',
        partNum: 'Kimtigo-16G-2666',
        serialNum: 'KMTG001',
        voltageConfigured: 1.2,
        voltageMin: 1.2,
        voltageMax: 1.2
      },
      {
        size: 17179869184,
        bank: 'BANK 0/1',
        type: 'DDR4',
        ecc: false,
        clockSpeed: 2666,
        formFactor: 'DIMM',
        manufacturer: 'Kimtigo Semiconductor (HK) Limited',
        partNum: 'Kimtigo-16G-2666',
        serialNum: 'KMTG001',
        voltageConfigured: 1.2,
        voltageMin: 1.2,
        voltageMax: 1.2
      },
      {
        size: 17179869184,
        bank: 'BANK 1/0',
        type: 'DDR4',
        ecc: false,
        clockSpeed: 3200,
        formFactor: 'DIMM',
        manufacturer: 'Samsung Electronics',
        partNum: 'M378A2K43CB1-CTD',
        serialNum: 'SAMSUNG002',
        voltageConfigured: 1.35,
        voltageMin: 1.35,
        voltageMax: 1.35
      },
      {
        size: 8589934592,
        bank: 'BANK 1/1',
        type: 'DDR4',
        ecc: true,
        clockSpeed: 2666,
        formFactor: 'DIMM',
        manufacturer: 'Micron Technology',
        partNum: 'MTA18ASF2G72PDZ-2G6E1',
        serialNum: 'MICRON003',
        voltageConfigured: 1.2,
        voltageMin: 1.2,
        voltageMax: 1.2
      },
      {
        size: 8589934592,
        bank: 'BANK 2/0',
        type: 'DDR4',
        ecc: true,
        clockSpeed: 2666,
        formFactor: 'DIMM',
        manufacturer: 'Micron Technology',
        partNum: 'MTA18ASF2G72PDZ-2G6E1',
        serialNum: 'MICRON003',
        voltageConfigured: 1.2,
        voltageMin: 1.2,
        voltageMax: 1.2
      },
      {
        size: 34359738368,
        bank: 'BANK 2/1',
        type: 'DDR4',
        ecc: false,
        clockSpeed: 2933,
        formFactor: 'DIMM',
        manufacturer: 'SK Hynix',
        partNum: 'HMA82GU6CJR8N-VK',
        serialNum: 'HYNIX004',
        voltageConfigured: 1.2,
        voltageMin: 1.2,
        voltageMax: 1.2
      },
      {
        size: 17179869184,
        bank: 'BANK 3/0',
        type: 'DDR4',
        ecc: false,
        clockSpeed: 3600,
        formFactor: 'SODIMM',
        manufacturer: 'Crucial Technology',
        partNum: 'CT16G4SFD824A',
        serialNum: 'CRUCIAL005',
        voltageConfigured: 1.2,
        voltageMin: 1.2,
        voltageMax: 1.2
      },
      {
        size: 17179869184,
        bank: 'BANK 3/1',
        type: 'DDR4',
        ecc: false,
        clockSpeed: 3600,
        formFactor: 'SODIMM',
        manufacturer: 'Crucial Technology',
        partNum: 'CT16G4SFD824A',
        serialNum: 'CRUCIAL005',
        voltageConfigured: 1.2,
        voltageMin: 1.2,
        voltageMax: 1.2
      },
      {
        size: 17179869184,
        bank: 'BANK 4/0',
        type: 'DDR4',
        ecc: false,
        clockSpeed: 3600,
        formFactor: 'SODIMM',
        manufacturer: 'Crucial Technology',
        partNum: 'CT16G4SFD824A',
        serialNum: 'CRUCIAL005',
        voltageConfigured: 1.2,
        voltageMin: 1.2,
        voltageMax: 1.2
      },
      {
        size: 17179869184,
        bank: 'BANK 4/1',
        type: 'DDR4',
        ecc: false,
        clockSpeed: 3600,
        formFactor: 'SODIMM',
        manufacturer: 'Crucial Technology',
        partNum: 'CT16G4SFD824A',
        serialNum: 'CRUCIAL005',
        voltageConfigured: 1.2,
        voltageMin: 1.2,
        voltageMax: 1.2
      },
      {
        size: 17179869184,
        bank: 'BANK 5/0',
        type: 'DDR4',
        ecc: false,
        clockSpeed: 3600,
        formFactor: 'SODIMM',
        manufacturer: 'Crucial Technology',
        partNum: 'CT16G4SFD824A',
        serialNum: 'CRUCIAL005',
        voltageConfigured: 1.2,
        voltageMin: 1.2,
        voltageMax: 1.2
      },
      {
        size: 17179869184,
        bank: 'BANK 5/1',
        type: 'DDR4',
        ecc: false,
        clockSpeed: 3600,
        formFactor: 'SODIMM',
        manufacturer: 'Crucial Technology',
        partNum: 'CT16G4SFD824A',
        serialNum: 'CRUCIAL005',
        voltageConfigured: 1.2,
        voltageMin: 1.2,
        voltageMax: 1.2
      }
    ],
    diskLayout: [
      {
        primary: true,
        device: '\\\\.\\PHYSICALDRIVE2',
        type: 'SSD',
        name: 'INTEL SSDPEKKW512G8',
        vendor: 'INTEL',
        size: 512105932800,
        bytesPerSector: 512,
        totalCylinders: 62260,
        totalHeads: 255,
        totalSectors: 1000206900,
        totalTracks: 15876300,
        tracksPerCylinder: 255,
        sectorsPerTrack: 63,
        firmwareRevision: '005C',
        serialNum: '0000_0000_0100_0000_E4D2_5C8F_9D36_5001.',
        interfaceType: 'NVMe',
        smartStatus: 'Ok',
        temperature: null
      },
      {
        primary: false,
        device: '\\\\.\\PHYSICALDRIVE1',
        type: 'SSD',
        name: 'Phison SM280128GPTCB2T-S112610',
        vendor: '',
        size: 128034708480,
        bytesPerSector: 512,
        totalCylinders: 15566,
        totalHeads: 255,
        totalSectors: 250067790,
        totalTracks: 3969330,
        tracksPerCylinder: 255,
        sectorsPerTrack: 63,
        firmwareRevision: 'SBFM61.0',
        serialNum: '8EC60776124800204151',
        interfaceType: 'SATA',
        smartStatus: 'Ok',
        temperature: null
      },
      {
        primary: false,
        device: '\\\\.\\PHYSICALDRIVE0',
        type: 'HD',
        name: 'HGST HTS721010A9E630',
        vendor: '',
        size: 1000202273280,
        bytesPerSector: 512,
        totalCylinders: 121601,
        totalHeads: 255,
        totalSectors: 1953520065,
        totalTracks: 31008255,
        tracksPerCylinder: 255,
        sectorsPerTrack: 63,
        firmwareRevision: 'JB0OA3U0',
        serialNum: 'JR1004D31B449M',
        interfaceType: 'SATA',
        smartStatus: 'Ok',
        temperature: null
      }
    ],
    audio: [
      {
        id: 'HDAUDIO\\FUNC_01&VEN_10DE&DEV_0099&SUBSYS_1458407D&REV_1001\\5&16B39C4E&0&0001',
        name: 'NVIDIA High Definition Audio',
        manufacturer: 'NVIDIA',
        revision: null,
        driver: null,
        default: null,
        channel: null,
        type: 'Sound Driver',
        in: null,
        out: null,
        status: '3'
      },
      {
        id: 'ROOT\\UNNAMED_DEVICE\\0000',
        name: 'NVIDIA Virtual Audio Device (Wave Extensible) (WDM)',
        manufacturer: 'NVIDIA',
        revision: null,
        driver: null,
        default: null,
        channel: null,
        type: '',
        in: null,
        out: null,
        status: '3'
      },
      {
        id: 'HDAUDIO\\FUNC_01&VEN_10EC&DEV_0897&SUBSYS_1458A194&REV_1004\\4&3A44A74C&0&0001',
        name: 'Realtek High Definition Audio',
        manufacturer: 'Realtek',
        revision: null,
        driver: null,
        default: null,
        channel: null,
        type: 'Sound Driver',
        in: null,
        out: null,
        status: '3'
      },
      {
        id: 'ROOT\\MEDIA\\0000',
        name: 'WO Mic Device',
        manufacturer: 'Wolicheng Tech Ltd.',
        revision: null,
        driver: null,
        default: null,
        channel: null,
        type: 'Microphone',
        in: null,
        out: null,
        status: '3'
      }
    ],
    bluetooth: [],
    usb: [
      {
        bus: null,
        deviceId: 'USB\\VID_046D&PID_C53F&MI_00\\6&1AA082A5&1&0000',
        id: 1,
        name: '增强型(101 或 102 键)',
        type: 'Keyboard',
        removable: null,
        vendor: null,
        manufacturer: '',
        maxPower: null,
        serialNumber: null
      },
      {
        bus: null,
        deviceId: 'USB\\VID_0416&PID_C345&MI_00\\6&15B0E55&0&0000',
        id: 2,
        name: '增强型(101 或 102 键)',
        type: 'Keyboard',
        removable: null,
        vendor: null,
        manufacturer: '',
        maxPower: null,
        serialNumber: null
      },
      {
        bus: null,
        deviceId: 'PCI\\VEN_10DE&DEV_1AEC&SUBSYS_407D1458&REV_A1\\4&AA66160&0&0208',
        id: 3,
        name: 'NVIDIA USB 3.10 可扩展主机控制器 - 1.10 (Microsoft)',
        type: 'Controller',
        removable: null,
        vendor: null,
        manufacturer: '通用 USB xHCI 主机控制器',
        maxPower: null,
        serialNumber: null
      },
      {
        bus: null,
        deviceId: 'PCI\\VEN_10DE&DEV_1AED&SUBSYS_407D1458&REV_A1\\4&AA66160&0&0308',
        id: 4,
        name: 'NVIDIA USB Type-C Port Policy Controller',
        type: 'Controller',
        removable: null,
        vendor: null,
        manufacturer: 'NVIDIA',
        maxPower: null,
        serialNumber: null
      },
      {
        bus: null,
        deviceId: 'PCI\\VEN_8086&DEV_7AE0&SUBSYS_50071458&REV_11\\3&11583659&0&A0',
        id: 5,
        name: 'Intel(R) USB 3.20 可扩展主机控制器 - 1.20 (Microsoft)',
        type: 'Controller',
        removable: null,
        vendor: null,
        manufacturer: '通用 USB xHCI 主机控制器',
        maxPower: null,
        serialNumber: null
      },
      {
        bus: null,
        deviceId: 'USB\\VID_05E3&PID_0608\\5&3A692CE1&0&9',
        id: 6,
        name: '通用 USB 集线器',
        type: 'Hub',
        removable: null,
        vendor: null,
        manufacturer: '',
        maxPower: null,
        serialNumber: null
      },
      {
        bus: null,
        deviceId: 'USB\\VID_0416&PID_C345\\5&3A692CE1&0&8',
        id: 7,
        name: 'USB Composite Device',
        type: 'Hub',
        removable: null,
        vendor: null,
        manufacturer: '',
        maxPower: null,
        serialNumber: null
      },
      {
        bus: null,
        deviceId: 'USB\\ROOT_HUB30\\5&3195F4D0&0&0',
        id: 8,
        name: 'USB 根集线器(USB 3.0)',
        type: 'Hub',
        removable: null,
        vendor: null,
        manufacturer: '',
        maxPower: null,
        serialNumber: null
      },
      {
        bus: null,
        deviceId: 'USB\\ROOT_HUB30\\4&1A408FEE&0&0',
        id: 9,
        name: 'USB 根集线器(USB 3.0)',
        type: 'Hub',
        removable: null,
        vendor: null,
        manufacturer: '',
        maxPower: null,
        serialNumber: null
      },
      {
        bus: null,
        deviceId: 'USB\\VID_05E3&PID_0620\\5&3A692CE1&0&17',
        id: 10,
        name: '通用 SuperSpeed USB 集线器',
        type: 'Hub',
        removable: null,
        vendor: null,
        manufacturer: '',
        maxPower: null,
        serialNumber: null
      },
      {
        bus: null,
        deviceId: 'USB\\VID_05E3&PID_0610\\5&3A692CE1&0&1',
        id: 11,
        name: '通用 USB 集线器',
        type: 'Hub',
        removable: null,
        vendor: null,
        manufacturer: '',
        maxPower: null,
        serialNumber: null
      },
      {
        bus: null,
        deviceId: 'USB\\VID_05E3&PID_0610\\5&3A692CE1&0&7',
        id: 12,
        name: '通用 USB 集线器',
        type: 'Hub',
        removable: null,
        vendor: null,
        manufacturer: '',
        maxPower: null,
        serialNumber: null
      }
    ],
    printer: [
      {
        id: 1,
        name: 'OneNote for Windows 10',
        model: 'Microsoft Software Printer Driver',
        uri: null,
        uuid: null,
        status: 'Idle',
        local: true,
        default: false,
        shared: false
      },
      {
        id: 2,
        name: 'Microsoft XPS Document Writer',
        model: 'Microsoft XPS Document Writer v4',
        uri: null,
        uuid: null,
        status: 'Idle',
        local: true,
        default: false,
        shared: false
      },
      {
        id: 3,
        name: 'Microsoft Print to PDF',
        model: 'Microsoft Print To PDF',
        uri: null,
        uuid: null,
        status: 'Idle',
        local: true,
        default: true,
        shared: false
      },
      {
        id: 4,
        name: 'Fax',
        model: 'Microsoft Shared Fax Driver',
        uri: null,
        uuid: null,
        status: 'Idle',
        local: true,
        default: false,
        shared: false
      }
    ]
  }
}
